cli: Remove usage of deprecated restrict
restrict was removed in o/xenstored upstream in 2017 in
dbc84d2983969bb47d294131ed9e6bbbdc2aec49, and in ocaml-xenstore recently.

Fixes this build error:
    dune build @install --profile=release
    File "cli/xs_client_cli.ml", line 224, characters 22-30:
    224 |       | Some domid -> restrict xs (int_of_string domid)
                                ^^^^^^^^
    Error: Unbound value restrict

Signed-off-by: Andrii Sultanov <andriy.sultanov@vates.tech>